<?php
declare(strict_types=1);
$username = isset($_GET['username']) ? trim($_GET['username']) : '';
$locale = ($_GET['lang'] ?? 'fa') === 'en' ? 'en' : 'fa';
$dir = $locale === 'fa' ? 'rtl' : 'ltr';
if ($username === '') { http_response_code(400); echo 'username is required'; exit; }
$labels = $locale === 'fa'
 ? ['user_info'=>'اطلاعات کاربر','group_list'=>'لیست گروه','attributes'=>'ویژگی‌ها','connection_logs'=>'لاگ اتصال','credit_changes'=>'تغییرات اعتبار','username'=>'نام کاربری','password'=>'رمز عبور','status'=>'قفل کاربر','locked'=>'قفل‌شده','enabled'=>'قفل نشده','configured'=>'تنظیم شده','not_configured'=>'تنظیم نشده','name'=>'نام','value'=>'مقدار','session'=>'اتصال','ras'=>'RAS','started'=>'ورود','time'=>'زمان','amount'=>'اعتبار','kind'=>'نوع','reference'=>'توضیحات','edit'=>'ویرایش','back'=>'بازگشت','none'=>'موردی وجود ندارد','loading'=>'در حال بارگذاری...','not_found'=>'کاربر پیدا نشد','load_error'=>'دریافت اطلاعات کاربر ناموفق بود']
 : ['user_info'=>'User Information','group_list'=>'Group List','attributes'=>'Attributes','connection_logs'=>'Connection Logs','credit_changes'=>'Credit Changes','username'=>'Username','password'=>'Password','status'=>'User Lock','locked'=>'Locked','enabled'=>'Unlocked','configured'=>'Configured','not_configured'=>'Not configured','name'=>'Name','value'=>'Value','session'=>'Connection','ras'=>'RAS','started'=>'Login','time'=>'Time','amount'=>'Credit','kind'=>'Action','reference'=>'Comment','edit'=>'Edit','back'=>'Back','none'=>'No records','loading'=>'Loading...','not_found'=>'User not found','load_error'=>'Unable to load user'];
?><!doctype html><html lang="<?= htmlspecialchars($locale, ENT_QUOTES) ?>" dir="<?= $dir ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= htmlspecialchars($labels['user_info']) ?> · ATD Radius</title>
<style>
:root{font-family:Inter,system-ui,sans-serif;color:#172033;background:#f5f7fb;--surface:#fff;--line:#e6eaf1;--muted:#697386;--accent:#315efb;--danger:#c53b45;--ok:#16855b}@media(prefers-color-scheme:dark){:root{color:#edf1f8;background:#0f131a;--surface:#171c25;--line:#293241;--muted:#a6b0c1;--accent:#6f8cff}}*{box-sizing:border-box}body{margin:0}.shell{max-width:1440px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;gap:16px;margin-bottom:22px}.title{display:flex;align-items:center;gap:12px}.avatar{width:44px;height:44px;border-radius:14px;background:var(--accent);color:#fff;display:grid;place-items:center;font-weight:800}.title h1{margin:0;font-size:26px}.sub,.crumb,.label,.empty{color:var(--muted);font-size:13px}.toolbar{display:flex;gap:8px}.btn{border:1px solid var(--line);background:var(--surface);color:inherit;padding:9px 13px;border-radius:10px;font-weight:700}.btn.primary{background:var(--accent);border-color:var(--accent);color:#fff}.grid{display:grid;grid-template-columns:1.35fr 1fr;gap:16px}.card{background:var(--surface);border:1px solid var(--line);border-radius:16px;padding:18px}.wide{grid-column:1/-1}.card h2{font-size:15px;margin:0 0 14px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.stat{border:1px solid var(--line);border-radius:12px;padding:13px}.stat b{font-size:20px}.stat span{display:block;color:var(--muted);font-size:12px;margin-top:4px}.row{display:flex;justify-content:space-between;gap:12px;padding:11px 0;border-bottom:1px solid var(--line)}.row:last-child{border-bottom:0}.value{font-weight:650;text-align:right}.pill{display:inline-flex;padding:5px 9px;border-radius:999px;font-size:12px;font-weight:700;background:rgba(22,133,91,.12);color:var(--ok)}.table{width:100%;border-collapse:collapse;font-size:13px}.table th,.table td{text-align:start;padding:10px;border-bottom:1px solid var(--line)}.table th{color:var(--muted);font-size:11px;text-transform:uppercase}.error{padding:14px;color:var(--danger)}@media(max-width:850px){.shell{padding:14px}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.stats{grid-template-columns:repeat(2,1fr)}.top{flex-direction:column}.toolbar{width:100%}.btn{flex:1}}
</style></head><body><div class="shell" id="app"><div class="empty"><?= htmlspecialchars($labels['loading']) ?></div></div>
<script>
const username=<?php echo json_encode($username,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); ?>;
const labels=<?php echo json_encode($labels,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); ?>;
const app=document.getElementById('app');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const empty=t=>'<div class="empty">'+esc(t||labels.none)+'</div>';
const rows=(items,fn)=>items.length?items.map(fn).join(''):empty(labels.none);
async function load(){
 try{
  const r=await fetch('/api/v1/users/'+encodeURIComponent(username)+'/detail',{headers:{Accept:'application/json'}});
  if(!r.ok)throw new Error(r.status===404?labels.not_found:labels.load_error);
  const u=await r.json();
  const nav='users.php?lang=<?php echo $locale; ?>';
  let html='<header class="top"><div><div class="crumb">'+esc(labels.user_info)+' / '+esc(u.username)+'</div><div class="title"><div class="avatar">'+esc(u.username.slice(0,1).toUpperCase())+'</div><div><h1>'+esc(u.username)+' <span class="pill">'+esc(u.locked?labels.locked:labels.enabled)+'</span></h1><div class="sub">'+esc(labels.user_info)+' · '+esc(u.id)+'</div></div></div></div><div class="toolbar"><button class="btn" onclick="location.href=\''+nav+'\'">'+esc(labels.back)+'</button><button class="btn primary" onclick="alert(\'Edit User Information\')">'+esc(labels.edit)+'</button></div></header>';
  html+='<main class="grid">';
  html+='<section class="card wide"><h2>'+esc(labels.user_info)+'</h2><div class="stats"><div class="stat"><b>'+u.groups.length+'</b><span>'+esc(labels.group_list)+'</span></div><div class="stat"><b>'+u.connection_logs.length+'</b><span>'+esc(labels.connection_logs)+'</span></div><div class="stat"><b>'+(u.has_password?esc(labels.configured):esc(labels.not_configured))+'</b><span>'+esc(labels.password)+'</span></div><div class="stat"><b>'+esc(u.locked?labels.locked:labels.enabled)+'</b><span>'+esc(labels.status)+'</span></div></div></section>';
  html+='<section class="card"><h2>'+esc(labels.user_info)+'</h2><div class="row"><span class="label">'+esc(labels.username)+'</span><span class="value">'+esc(u.username)+'</span></div><div class="row"><span class="label">'+esc(labels.password)+'</span><span class="value">'+(u.has_password?esc(labels.configured):esc(labels.not_configured))+'</span></div></section>';
  html+='<section class="card"><h2>'+esc(labels.group_list)+'</h2>'+rows(u.groups,g=>'<div class="row"><span><b>'+esc(g.name)+'</b><div class="label">'+esc(g.comment||'')+'</div></span></div>')+'</section>';
  html+='<section class="card wide"><h2>'+esc(labels.attributes)+'</h2>'+rows(u.attributes,a=>'<div class="row"><span>'+esc(a.name)+'</span><span class="value">'+esc(a.value)+'</span></div>')+'</section>';
  html+='<section class="card wide"><h2>'+esc(labels.connection_logs)+'</h2>'+rows(u.connection_logs,x=>'<div class="row"><span>'+esc(x.id)+' · '+esc(x.ras_id??'—')+'</span><span>'+esc(x.login_time||'—')+' → '+esc(x.logout_time||'—')+' · '+esc(x.credit_used??'—')+'</span></div>')+'</section>';
  html+='<section class="card wide"><h2>'+esc(labels.credit_changes)+'</h2>'+rows(u.credit_changes,x=>'<div class="row"><span>'+esc(x.change_time||'—')+' · '+esc(x.action??'—')+'</span><span>'+esc(x.per_user_credit??'—')+' · '+esc(x.comment||'')+'</span></div>')+'</section>';
  html+='</main>'; app.innerHTML=html;
 }catch(e){app.innerHTML='<div class="error">'+esc(e.message)+'</div>'}
}
load();
</script></body></html>